clear all
dd = '';
fd = '';
fs = 25; fs2 = 15; lw = 4; lw2 = 2; ms = 20; ms2 = 9;

load([dd 'native_scan.mat']);
aks_native = aks;
load([dd 'synex_scan.mat']);
aks_synex = aks;
load([dd 'pi2_inflection.mat']);
load([dd 'pi2_dkl.mat']);
load([dd 'native_fit_cdf.mat']);
kstar_native1 = kstar;
load([dd 'native_fit_cdf2.mat']);
kstar_native2 = kstar;
load([dd 'native_fit_cdf3.mat']);
kstar_native3 = kstar;
load([dd 'synex_fit_cdf.mat']);
kstar_synex1 = kstar;
load([dd 'synex_fit_cdf2.mat']);
kstar_synex2 = kstar;
load([dd 'pi2_native_dkl_exp_cdf.mat']);
pi2_native_dkl_exp1 = pi2_native_dkl_exp;
load([dd 'pi2_native_dkl_exp_cdf2.mat']);
pi2_native_dkl_exp2 = pi2_native_dkl_exp;
load([dd 'pi2_native_dkl_exp_cdf3.mat']);
pi2_native_dkl_exp3 = pi2_native_dkl_exp;
load([dd 'pi2_synex_dkl_exp_cdf.mat']);
pi2_synex_dkl_exp1 = pi2_synex_dkl_exp;
load([dd 'pi2_synex_dkl_exp_cdf2.mat']);
pi2_synex_dkl_exp2 = pi2_synex_dkl_exp;
load([dd 'error_native.mat'])
kcross_native1 = kcross;
load([dd 'error_native2.mat'])
kcross_native2 = kcross;
load([dd 'error_native3.mat'])
kcross_native3 = kcross;
load([dd 'error_synex.mat'])
kcross_synex1 = kcross;
load([dd 'error_synex2.mat'])
kcross_synex2 = kcross;

ak1_native = .00072;
ak1_synex = .033;
ak2_native = .0033;
ak2_synex = .7565;
ak1bar_native = ak1_native/ak2_native;
ak1bar_synex = ak1_synex/ak2_synex;
akbar_native = aks_native/ak2_native;
akbar_synex = aks_synex/ak2_synex;
akbar_native_exp1 = akbar_native(kstar_native1);
akbar_native_exp2 = akbar_native(kstar_native2);
akbar_native_exp3 = akbar_native(kstar_native3);
akbar_synex_exp1 = akbar_synex(kstar_synex1);
akbar_synex_exp2 = akbar_synex(kstar_synex2);

% highest-IPTG distributions are clearly unimodal by eye
% this is not capturable by dkl analysis (two peaks divided 50/50)
% so put it in by hand:
pi2_synex_dkl_exp1(5) = 1;
pi2_synex_dkl_exp2(2) = 1;
pi2_native_dkl_exp3(1) = 1;

% plot only dkl; jump discontinuously to 1 according to inflection
kjump_native = min(find(pi2_native_inflection == 1));
akbar_native = akbar_native([1:kjump_native kjump_native:end]);
pi2_native_theory = [pi2_native_dkl(1:kjump_native) ...
                    ones(1,length(akbar_native)-kjump_native)];
kjump_synex = min(find(pi2_synex_inflection == 1));
akbar_synex = akbar_synex([1:kjump_synex kjump_synex:end]);
pi2_synex_theory = [pi2_synex_dkl(1:kjump_synex) ...
                    ones(1,length(akbar_synex)-kjump_synex)];

figure(1); clf
h = semilogx(akbar_native,pi2_native_theory,'b-',...
             akbar_native_exp1,pi2_native_dkl_exp1,'bo',...
             akbar_synex,pi2_synex_theory,'r-',...
             akbar_synex_exp1,pi2_synex_dkl_exp1,'ro',...
             akbar_native_exp2,pi2_native_dkl_exp2,'bo',...
             akbar_native_exp3,pi2_native_dkl_exp3,'bo',...
             akbar_synex_exp2,pi2_synex_dkl_exp2,'ro',...
             [akbar_native(kcross_native1{1}(1)) ...
              akbar_native(kcross_native1{1}(2))],...
             [pi2_native_dkl_exp1(1) pi2_native_dkl_exp1(1)],'b-',...
             [akbar_native(kcross_native1{2}(1)) ...
              akbar_native(kcross_native1{2}(2))],...
             [pi2_native_dkl_exp1(2) pi2_native_dkl_exp1(2)],'b-',...
             [akbar_native(kcross_native1{3}(1)) ...
              akbar_native(kcross_native1{3}(2))],...
             [pi2_native_dkl_exp1(3) pi2_native_dkl_exp1(3)],'b-',...
             [akbar_native(kcross_native1{4}(1)) ...
              akbar_native(kcross_native1{4}(2))],...
             [pi2_native_dkl_exp1(4) pi2_native_dkl_exp1(4)],'b-',...
             [akbar_synex(kcross_synex1{1}(1)) ...
              akbar_synex(kcross_synex1{1}(2))],...
             [pi2_synex_dkl_exp1(1) pi2_synex_dkl_exp1(1)],'r-',...
             [akbar_synex(kcross_synex1{2}(1)) ...
              akbar_synex(kcross_synex1{2}(2))],...
             [pi2_synex_dkl_exp1(2) pi2_synex_dkl_exp1(2)],'r-',...
             [akbar_synex(kcross_synex1{3}(1)) ...
              akbar_synex(kcross_synex1{3}(2))],...
             [pi2_synex_dkl_exp1(3) pi2_synex_dkl_exp1(3)],'r-',...
             [akbar_synex(kcross_synex1{4}(1)) ...
              akbar_synex(kcross_synex1{4}(2))],...
             [pi2_synex_dkl_exp1(4) pi2_synex_dkl_exp1(4)],'r-',...
             [akbar_synex(kcross_synex1{5}(1)) ...
              akbar_synex(kcross_synex1{5}(2))],...
             [pi2_synex_dkl_exp1(5) pi2_synex_dkl_exp1(5)],'r-',...
             [akbar_native(kcross_native2{1}(1)) ...
              akbar_native(kcross_native2{1}(2))],...
             [pi2_native_dkl_exp2(1) pi2_native_dkl_exp2(1)],'b-',...
             [akbar_native(kcross_native2{2}(1)) ...
              akbar_native(kcross_native2{2}(2))],...
             [pi2_native_dkl_exp2(2) pi2_native_dkl_exp2(2)],'b-',...
             [akbar_native(kcross_native2{3}(1)) ...
              akbar_native(kcross_native2{3}(2))],...
             [pi2_native_dkl_exp2(3) pi2_native_dkl_exp2(3)],'b-',...
             [akbar_synex(kcross_synex2{1}(1)) ...
              akbar_synex(kcross_synex2{1}(2))],...
             [pi2_synex_dkl_exp2(1) pi2_synex_dkl_exp2(1)],'r-',...
             [akbar_synex(kcross_synex2{2}(1)) ...
              akbar_synex(kcross_synex2{2}(2))],...
             [pi2_synex_dkl_exp2(2) pi2_synex_dkl_exp2(2)],'r-',...
             [akbar_native(kcross_native3{1}(1)) ...
              akbar_native(kcross_native3{1}(2))],...
             [pi2_native_dkl_exp3(1) pi2_native_dkl_exp3(1)],'b-',...
             [1 1],[-.05 1.05],'k--');

ylim([-.05 1.05])
xlim([2e-2 4e1])
set(h,'markersize',ms2,'linewidth',lw)
set(h(8:end),'linewidth',lw2)
set(h([2 5 6]),'markerfacecolor','b')
set(h([4 7]),'markerfacecolor','r')
legend(h([1:4 end]),{'Native: theory',...
                    'Native: experiment',...
                    'SynEx: theory',...
                    'SynEx: experiment',...
                    'Deterministic transition'},...
       'location','nw','fontsize',fs2)
xlabel({'$\qquad\qquad$ ComK induction rate, $a_k$',...
    '(normalized by deterministic transition value)'},...
    'fontsize',fs,'interpreter','latex','horizontalalignment','center')
ylabel('Fraction in responsive state, $f$',...
    'fontsize',fs,'interpreter','latex')
set(gca,'fontsize',fs2)
box on
print(gcf,'-depsc',...
      [fd 'fig5c.eps'])
